#配置端口
server:
  port: 8001
  servlet:
    context-path: /community

spring:
  #配置数据源
  datasource:
    #配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false
    username: root
    password: yuting
  # MailProperties
  mail:
    host: smtp.163.com
    port: 465
    username: ytvivian98@163.com
    #not the password but the authentiacte code
    password: YYTAHFSSIRXGHUVI
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  #RedisProperties
  redis:
    database: 11
    host: localhost
    port: 6379
 #kafka properties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
      #过时了
#  data:
#    elasticsearch:
#      cluster-name: newcoder
#      cluster-nodes: 127.0.0.1:9300
  elasticsearch:
    uris: 127.0.0.1:9200
    username: newcoder

    #TaskExecutionProperties
 task:
   execution:
     pool:
       core-size: 5
       max-size: 15
       queue-capacity: 100
   scheduling:
     pool:
       size: 5



#MyBatis-Plus相关配置
mybatis-plus:
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# commmunity
community:
  path:
    domain: http://localhost:8001
    upload: d:/javaTestCache/upload



