#配置端口
server:
  port: 8080
  servlet:
    context-path: /community

spring:
  #配置数据源
  datasource:
    #配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false
    username: root
    password: yuting
  # MailProperties
  mail:
    host: smtp.163.com
    port: 465
    username: ytvivian98@163.com
    #not the password but the authentiacte code
    password: YYTAHFSSIRXGHUVI
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true

#MyBatis-Plus相关配置
mybatis-plus:
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# commmunity
community:
  path:
    domain: http://localhost:8080

